name: soft_metatags
description: An enhanced Dart package with Rust for reading and writing audio file metadata.

homepage: https://softyes.com.br
repository: https://github.com/softyesti/soft_metatags

authors:
  - SoftYes TI
  - Jo√£o Sereia

version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.6
  lints: ^6.0.0
  very_good_analysis: ^10.0.0
