tab_spaces = 2
max_width = 80
edition = "2024"
wrap_comments = true
fn_single_line = true
format_strings = true
use_try_shorthand = true
where_single_line = true
reorder_impl_items = true
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
error_on_unformatted = true
error_on_line_overflow = true
brace_style = "PreferSameLine"
imports_granularity = "Module"
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
